name: fmtc_example
description: The example application for 'flutter_map_tile_caching', showcasing
  it's functionality and use-cases.
publish_to: "none"

version: 6.2.0+2

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=3.7.0"

dependencies:
  badges: ^3.1.1
  better_open_file: ^3.6.4
  connection_status_bar: ^1.1.6
  docking: ^1.15.0
  flutter:
    sdk: flutter
  flutter_analog_clock: ^1.0.3
  flutter_foreground_task: ^6.0.0
  flutter_map: ^5.0.0
  flutter_map_animations: ^0.4.1
  flutter_map_tile_caching:
    path: ../
  flutter_native_splash: ^2.3.6
  flutter_speed_dial: ^7.0.0
  google_fonts: ^5.0.0
  http: ^1.0.0
  intl: ^0.18.1
  latlong2: ^0.9.0
  libserialport: ^0.3.0+1
  osm_nominatim: ^2.0.1
  path: ^1.8.1
  pausable_timer: ^3.1.0+3
  provider: ^6.0.3
  scroll_loop_auto_scroll: ^0.0.5
  shared_preferences: ^2.0.15
  side_navigation: ^1.0.4
  stream_transform: ^2.0.0
  syncfusion_flutter_datagrid: ^23.2.4
  syncfusion_flutter_gauges: ^23.2.4
  validators: ^3.0.0
  version: ^3.0.2
  window_manager: ^0.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/icons/
    - assets/icons/
    - assets/
    - currentAppVersion.txt
flutter_native_splash:
  color: "#42a5f5"
  image: assets/MARS_ROBOTICS.jpg
  android: true
  ios: true
 